# Generated by Django 3.1.5 on 2021-02-09 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=10)),
                ('start', models.TimeField(null=True)),
                ('end', models.TimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=9, unique=True)),
                ('year', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], default='Freshman', max_length=10)),
                ('major', models.CharField(choices=[('English', 'English'), ('Business Administration', 'Business Administration'), ('Teaching', 'Teaching'), ('Information Technology', 'Information Technology'), ('Christian Studies', 'Christian Studies'), ('Bioscience', 'Bioscience'), ('Public Health', 'Public Health')], default='English', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_app.classcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default-user.png', null=True, upload_to='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Encoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.BinaryField()),
                ('face', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='face_app.face')),
            ],
        ),
        migrations.CreateModel(
            name='ClassDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, null=True)),
                ('classcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_app.classcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('entry', models.CharField(max_length=5)),
                ('classcourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='face_app.classcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_app.student')),
            ],
        ),
    ]
